title: Jakob's blog
owner: Jakob He
email: lewei.me@gmail.com
description: A description
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username: lewei_2020
github_username: leweii
disqus_username: 
# Build settings
markdown: kramdown
theme: minima

permalink: /:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
